name: the_last_bluetooth
description: "The last bluetooth plugin you'll ever need. Probably."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

  jni: ^0.13.0
  rxdart: '>=0.25.0 <1.0.0'
  collection: '>=1.15.0 <2.0.0'
  stream_channel: '>=2.0.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  jnigen: ^0.13.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
#  This is (90% sure) required when using jni
  plugin:
    platforms:
      android:
        ffiPlugin: true
